import type { Metadata } from 'next'
import localFont from 'next/font/local'
import '../globals.css'
import Header from '@/components/common/Header/Header'
import Footer from '@/components/common/Footer/Footer'

const geistSans = localFont({
  src: '../fonts/DarkerGrotesque-Medium.woff',
  variable: '--font-darker-grotesque-medium',
  weight: '500'
})
const geistMono = localFont({
  src: '../fonts/DarkerGrotesque-SemiBold.woff',
  variable: '--font-darker-grotesque-semi-bold',
  weight: '600'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <>
          <Header />
          {children}
          <Footer />
        </>
      </body>
    </html>
  )
}
